import type { TuningField } from '../../shared/contracts';
export const tuning: TuningField[] = [
  {
    key: 'player.walkSpeed',
    label: 'Walking speed',
    type: 'number',
    default: 2.8,
    min: 1.5,
    max: 4,
    step: 0.1,
    restart: true,
  },
  {
    key: 'player.runSpeed',
    label: 'Running speed',
    type: 'number',
    default: 4.2,
    min: 3,
    max: 6,
    step: 0.1,
    restart: true,
  },
  {
    key: 'vision.range',
    label: 'Detection range',
    type: 'number',
    default: 5,
    min: 3,
    max: 8,
    restart: true,
  },
  {
    key: 'vision.detectSeconds',
    label: 'Detection time',
    type: 'number',
    default: 0.8,
    min: 0.4,
    max: 2,
    step: 0.1,
    restart: true,
  },
  {
    key: 'encounter.clashSeconds',
    label: 'Clash duration',
    type: 'number',
    default: 5,
    min: 3,
    max: 10,
    restart: true,
  },
  {
    key: 'mode',
    label: 'Mode',
    type: 'select',
    default: 'story',
    options: ['story', 'standard', 'turn-assisted'],
    restart: true,
  },
  {
    key: 'presentation.assetVariant',
    label: 'Palette',
    type: 'select',
    default: 'A',
    options: ['A', 'B', 'C'],
    restart: false,
  },
];
